-- 23/03/2021

CREATE DATABASE notes;

USE notes;

CREATE TABLE user (
	id INT AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(60) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE note (
	id INT AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL,
	description LONGTEXT,
	id_user INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (id),
	FOREIGN KEY (id_user) REFERENCES user(id)
);